input {
  file {
    path => "D:/APISearch-Java-ES-Logstash-Kafka-Docker/es-logstash/data/test1.txt"
    start_position => "beginning"
    sincedb_path => "NUL"
    codec => json
  }
}

filter {
  date {
    match => ["timestamp", "UNIX", "ISO8601"]
    target => "timestamp"
  }

  mutate {
    convert => { "error_code" => "integer" }
  }
}

output {
  elasticsearch {
    hosts => ["http://103.21.149.190:9200"]
    index => "thangcv_test1"
    document_id => "%{trace_id}"   # dùng trace_id làm ID duy nhất
    user => "elastic"
    password => "M6a5K2XgHhWJYAZUsGF4mRc"
  }

  stdout {
    codec => rubydebug
  }
}
