spring:
  main:
    allow-circular-references: true

elasticsearch:
  host: elasticsearch
  port: 
  username: elastic
  password: M6a5K2XgHhWJYAZUsGF4mRc
  index:
    auto-create: true

  kafka:
    bootstrap-servers: 10.10.10.12:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      compression-type: gzip
      batch-size: 65536
      linger-ms: 20
      buffer-memory: 33554432

server:
  port: 8088
  address: 0.0.0.0

logging:
  level:
    org.springframework.data.elasticsearch: DEBUG
    org.elasticsearch: DEBUG

api:
  key:
    header: API-KEY
    clients:
      vnlink.vn: SSMEDIA
      VNLINK-GROUP: 8TRAVEL
